version: 2
jobs:
    build:
        docker:
            - image: debian:stretch

        steps:
            - checkout
            - run:
                name: Installing GCC
                command: 'apt-get update && apt-get install -y gcc g++'
            - run:
                name: Installing Essentials
                command: 'apt-get install build-essential' 
            - run:
                name: Build Binaries
                command: 'make all'
