version: 2
jobs:
    build:
        docker:
            - image:  circleci/buildpack-deps:bionic
        steps:
            - checkout
            - run:
                name: Install Build Essentials
                command: 'sudo apt install -y build-essential' 
            - run:
                name: Install Common Software Properties
                command: 'sudo apt-get install -y software-properties-common'   
            - run:
                name: Install Boost
                command: |
                    sudo add-apt-repository ppa:mhier/libboost-latest
                    sudo apt-get update
                    sudo apt-get install libboost1.68-dev
            - run:
                name: Build Binaries
                command: 'make all'
    static-analysis:
        docker:
            - image: circleci/buildpack-deps:bionic 
        steps:
            - checkout
            - run:
                name: Install cppcheck
                command: 'sudo apt-get install cppcheck'   
            - run:
                name: Run cppcheck
                command: 'cppcheck --error-exitcode=1 src'
            - run:
                name: Install Pip
                command: 'sudo apt install python3-pip' 
            - run:
                name: Install PyLint
                command: 'sudo pip3 install pylint'
            - run:
                name: Run Pylint
                command: 'pylint test/test_main.py'
workflows:
    version: 2
    build_and_analyze:
        jobs:
            - build
            - static-analysis
