version: 2
jobs:
    build:
        docker:
            - image:  circleci/buildpack-deps:bionic

        steps:
            - checkout
            - run:
                name: Install Build Essentials
                command: 'sudo apt install -y build-essential' 
            - run:
                name: Install Common Software Properties
                command: 'sudo apt-get install -y software-properties-common'   
            - run:
                name: Install Boost
                command: |
                    sudo add-apt-repository ppa:mhier/libboost-latest
                    sudo apt-get update
                    sudo apt-get install libboost1.68-dev
            - run:
                name: Building Binaries
                command: 'make all'
    static-analysis:
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run:
                name: Installing cppcheck
                command: 'apt-get install cppcheck'   
            - run:
                name: Running cppcheck
                command: 'cppcheck --error-exitcode=1 *.cpp'
