version: 2
jobs:
    build-and-test:
        docker:
            - image: circleci/buildpack-deps:bionic
        steps:
            - checkout
            - run:
                name: Install Build Essentials
                command: 'sudo apt install -y build-essential' 
            - run:
                name: Install Common Software Properties
                command: 'sudo apt-get install -y software-properties-common'   
            - run:
                name: Install Boost
                command: |
                    sudo add-apt-repository ppa:mhier/libboost-latest
                    sudo apt-get update
                    sudo apt-get install libboost1.68-dev
            - run:
                name: Build Binaries
                command: 'make all'
            - run:
                name: Install Python
                command: 'sudo apt-get update && sudo apt-get install python3'
            - run:
                name: Run Integration Tests
                command: 'make all && cd test && python test_main.py'
    static-analysis:
        docker:
            - image: circleci/buildpack-deps:bionic 
        steps:
            - checkout
            - run:
                name: Install cppcheck
                command: 'sudo apt-get install cppcheck'   
            - run:
                name: Run cppcheck
                command: 'cppcheck --error-exitcode=1 src'
            - run:
                name: Install Pip
                command: 'sudo apt install python3-pip'
            - run:
                name: Install cpplint
                command: 'sudo pip3 install cpplint'
            - run:
                name: Run cpplint
                command: 'cpplint --filter=-runtime/references,-build/c++11 --recursive */*'
            - run:
                name: Install PyLint
                command: 'sudo pip3 install pylint'
            - run:
                name: Run Pylint
                command: 'pylint test/test_main.py'
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-and-test
    static_analysis:
        jobs:
            - static-analysis
